.PHONY: all top_personality top_intelligence preference ability suitability

all: top_personality top_intelligence preference ability suitability

top_personality:
	@echo "Running top_personality.py..."
	@python top_personality.py

top_intelligence:
	@echo "Running top_intelligence.py..."
	@python top_intelligence.py

preference:
	@echo "Running preference.py..."
	@python preference.py

ability:
	@echo "Running ability.py..."
	@python ability.py

suitability:
	@echo "Running suitability.py..."
	@python suitability.py
